services:
  techchallenge:
    build: .
    hostname: techchallenge
    container_name: techchallenge
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:17.5
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: techchallenge
      POSTGRES_USER: tech
      POSTGRES_PASSWORD: challenge
